severity: CRITICAL,HIGH,MEDIUM
ignore-unfixed: false
vuln-type: os,library
secret-scanning:
  enabled: true
misconfiguration-scanning:
  enabled: true
  targets:
    - Dockerfile
    - Kubernetes
    - Terraform
ignore:
  - CVE-XXXX-XXXX # Example: Add specific CVEs to ignore here with justification
output:
  format: table