pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "my-django-app"
        AKS_CREDENTIALS = credentials('azure-aks-credentials')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'python manage.py test'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([string(credentialsId: 'azure-aks-credentials', variable: 'AKS_CREDENTIALS')]) {
                    sh '''
                    az aks get-credentials --resource-group my-resource-group --name my-aks-cluster
                    kubectl apply -f k8s/deployment.yaml
                    '''
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}